# Generated by Django 5.0.7 on 2024-07-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecificationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
            ],
            options={
                "verbose_name": "Specification Group",
                "verbose_name_plural": "Specification Groups",
                "db_table": "stuff_factory_specification_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                (
                    "phase",
                    models.IntegerField(
                        choices=[
                            (1, "Planning"),
                            (2, "PlanningReady"),
                            (3, "Design"),
                            (4, "DesignReady"),
                            (5, "Building"),
                            (6, "Built"),
                        ],
                        default=1,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        related_query_name="clone",
                        to="specifications.specification",
                        verbose_name="Cloned From",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specification",
                        related_query_name="specification",
                        to="specifications.specificationgroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specification",
                "verbose_name_plural": "Specifications",
                "db_table": "stuff_factory_specifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
