# Generated by Django 5.0.7 on 2024-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="description",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="selected_part",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Selected Part"
            ),
        ),
    ]
