LOGGER_NAME = "error_logger"

API_PREFIX = "api"
SWAGGER_API_VERSION = "v1"
SWAGGER_URL_PREFIX = f"{API_PREFIX}/{SWAGGER_API_VERSION}"

PASSWORD_MINIMUM_LENGTH = 8
PASSWORD_UPPER_AND_LOWER_REQUIRED = True
PASSWORD_NUMERIC_REQUIRED = True
PASSWORD_SPECIAL_CHAR_REQUIRED = True
